### ISSUE TITLE
Releasing on package.elm-lang.org ...

### ISSUE THREAD

**Issue by alltonp** [lorenzo/elm-webdriver#1]
Hi,

Awesome work. I was about to doing a webdriver wrapper myself, but it seems like you've already done the hardwork!

Are you planning to make it available as a package on http://package.elm-lang.org/ ?

Many thanks,

Paul

**Comment by lorenzo** [comment]
I don't think it will be possible to publish in the packages site, as it contains a Native module. You can install it using `npm install elm-webdriver`

**Comment by lorenzo** [comment]
Btw, since you were thinking of doing it yourself, maybe you want to help advancing this project?
