### ISSUE TITLE
init command is broken

### ISSUE THREAD

**Issue by tillydray** [lorenzo/elm-webdriver#10]
Per our brief conversation on Slack Elm#webdriver, the init command no longer does anything. Also, the instructions are different in GitHub and NPMjs.

**Comment by bitterjug** [comment]
I was just wondering where `init` had gone.

**Comment by lorenzo** [comment]
Do you want to hel me bringing it back? Haven’t had a lot of time lately. I can guide you if you need.

Otherwise you can just copy the example folder as your initial tests folder and modify at will.

**Comment by lorenzo** [comment]
I fixed this in version 3.0.3
