### ISSUE TITLE
src directory not installed 

### ISSUE THREAD

**Issue by bitterjug** [lorenzo/elm-webdriver#11]
I tried to install into an elm project today. I noticed #10 init is no longer available but that wasn't the main blocker.  I followed the instructions in the readme, but the `src` directory didn't get installed:
```
$ ls node_modules/elm-webdriver/
Api.md  bin  elm-stuff  example  package.json  Readme.md  webdriver-tests
```
So can't build the tests.

**Comment by lorenzo** [comment]
I definitely suck at npm. Sorry for the trouble, I’ll try to get that fixed tomorrow

**Comment by bitterjug** [comment]
I thought this was because `package.json` now contains `files` part:
```
  "files": [
    "bin",
    "Readme.md",
    "Api.md"
  ],
```
This [SO answer](https://stackoverflow.com/questions/40795836/how-do-you-use-the-files-and-directories-properties-in-package-json) says:

> That is, instead of including everything by default, if files array is specified everything is excluded by default and only those files explicitly listed will be included in the packaged tarball.

So i did `npm pack` in my copy of  `elm-webdriver`. But the tgz it created looked like this:
```
.
└── package
    ├── Api.md
    ├── bin
    │   └── elm-webdriver.js
    └── package.json
```
Which doesn't even include `Readme.md` so I'm afraid I don't even understand what is going on.

**Comment by lorenzo** [comment]
@bitterjug I published a new version. Can you verify it works for you?

**Comment by bitterjug** [comment]
Alright `src` is there now. 
I tried to install this in a clearn directory. I just made a directory and did `npm init` to create `package.json`. then did `npm install elm-webdriver`, created `tests/`, copied the templates there and replaced `Main.elm` with the sample as per readme. When I try to compile that, this happens:

```
[:~/workspace/elm/wdtest/tests] $ ../node_modules/.bin/elm-webdriver
Error: Your .elm/packages/ directory may be corrupted. I was led to believe that
lorenzo/elm-webdriver existed, but I could not find anything when I went to look
up the published versions of this package.


Failed to compile tests
```

Do I need to separately install elm test or something? [similar](https://github.com/gdotdesign/elm-github-install/issues/47)

**Comment by lorenzo** [comment]
@bitterjug there should be a different  `elm-package.json` for the tests folder should looks something like this: https://github.com/lorenzo/elm-webdriver/blob/master/templates/elm-package.json

The important line is this one: https://github.com/lorenzo/elm-webdriver/blob/master/templates/elm-package.json#L9

**Comment by bitterjug** [comment]
@lorenzo thanks for being so pro-active to fix this.

I have that. I mean I copied the one from [templates](https://github.com/lorenzo/elm-webdriver/tree/master/templates) which looks like this:
```json
{
  "version": "1.0.0",
  "summary": "Setup for running webdriver tests. DO NOT MODIFY THE REPOSITORY FIELD",
  "repository": "https://github.com/lorenzo/elm-webdriver.git",
  "license": "BSD3",
  "source-directories": [
    ".",
    "../src",
    "../node_modules/elm-webdriver/src"
  ],
  "exposed-modules": [],
  "native-modules": true,
  "dependencies": {
    "elm-community/elm-test": "3.0.0 <= v < 4.0.0",
    "elm-lang/core": "5.1.1 <= v < 6.0.0",
    "lorenzo/elm-webdriver": "3.0.0 <= v < 4.0.0"
  },
  "elm-version": "0.18.0 <= v < 0.19.0"
}
```
I tried `npm install elm-webdriver@2.0.2` and got a lot further. `init` worked, and  he tests compile and run:

```
2d [:~/dev/webdriver-tests] master* ± ../node_modules/.bin/elm-webdriver

0 - All Tests / Finding Elm Lang in Google
 ———————————————————————————————————————————————————————————— 0/8 (0%)
→ Waiting for start

1 - All Tests / Finding hacker news in Google
 ———————————————————————————————————————————————————————————— 0/8 (0%)
→ Waiting for start
```

**Comment by lorenzo** [comment]
selenium is not started automatically for you (on my todo list). Have a look at the reasmenin how to inatall it and run it.

The selenium server needs to be running before executing the tests

**Comment by lorenzo** [comment]
I’ll investigate by installing it myself with nom why this new version does not work. Thanks for your patience

**Comment by bitterjug** [comment]
The selenium thing (that I ran into on 2.0.2) is a different issue. (I had actually run the standalone server in another window before I started this but I dont want to look into that here). 

The issue we're facing really is why 3.0.1 doesn't compile stuff. 
So if we can work out together why that's not working for me that'd be great. 

Thanks for your help.

**Comment by lorenzo** [comment]
@bitterjug I published 3.0.3, I think this is fixed now.

**Comment by bitterjug** [comment]
@lorenzo yeah 3.0.3 compiles tests that run, and the init command also works. 
Thanks for fixing this.

**Comment by lorenzo** [comment]
Great news! Thanks for confirming it worked for you
