### ISSUE TITLE
Installing it on Windows

### ISSUE THREAD

**Issue by NicolasUmiastowski** [lorenzo/elm-webdriver#2]
[npm-debug.log.zip](https://github.com/lorenzo/elm-webdriver/files/425921/npm-debug.log.zip)

I've had so much difficulties installing elm-webdriver on windows that I gave up. 
I even thought I should install Visual Studio, but I kepp having errors at the install

Here is the last error message after launching `npm install elm-webdriver`
I have Node.js latest version and python 2.7 installed, and visual studio 2015.

 Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\numiastowski>cd documents

C:\Users\numiastowski\Documents>cd elm

C:\Users\numiastowski\Documents\elm>npm install elm-webdriver

> get-cursor-position@1.0.1 install C:\Users\numiastowski\Documents\elm\node_mod
> ules\get-cursor-position
> node-gyp rebuild

C:\Users\numiastowski\Documents\elm\node_modules\get-cursor-position>if not defi
ned npm_config_node_gyp (node "C:\Users\numiastowski\AppData\Roaming\npm\node_mo
dules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
 )  else (node "" rebuild )
Génération des projets individuellement dans cette solution. Pour activer la gén
ération en parallèle, ajoutez le commutateur "/m".
  pos.cc
  win_delay_load_hook.cc
..\src\pos.cc(6): fatal error C1083: Impossible d'ouvrir le fichier include : '
termios.h' : No such file or directory [C:\Users\numiastowski\Documents\elm\nod
e_modules\get-cursor-position\build\pos.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\numiastowski\AppData\Roaming
\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\numiastowski\
\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp
.js" "rebuild"
gyp ERR! cwd C:\Users\numiastowski\Documents\elm\node_modules\get-cursor-positio
n
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\numiastowski\D
ocuments\elm\package.json'
npm WARN elm No description
npm WARN elm No repository field.
npm WARN elm No README data
npm WARN elm No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\numiastowski\Ap
pData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "elm-webdrive
r"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! get-cursor-position@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the get-cursor-position@1.0.1 install script 'node-gyp rebuil
d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the get-cursor-position p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs get-cursor-position
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls get-cursor-position
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\numiastowski\Documents\elm\npm-debug.log

C:\Users\numiastowski\Documents\elm>

**Comment by lorenzo** [comment]
I haven't use windows in 14 years, but I would suggest trying the new bash support for windows, as it will probably make things a lot easier

https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by lorenzo** [comment]
Looking at the error log you have, it seems like it is indeed my use of bash dependent libraries what are creating the error.

**Comment by NicolasUmiastowski** [comment]
now I could install it with no problem :) very cool :)
