### ISSUE TITLE
binary not working on OS X Sierra

### ISSUE THREAD

**Issue by knewter** [lorenzo/elm-webdriver#3]
Not sure if this is a problem anywhere else, but at least on sierra the binary won't work due to `readlink` failing to have a `-f` option:

```
$ readlink -f foo
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by knewter** [comment]
https://github.com/lorenzo/elm-webdriver/blob/master/bin/elm-webdriver#L3

**Comment by lorenzo** [comment]
Thanks, I tagged `1.6.2` with a fix for this issue
